### ISSUE TITLE
Cannot read properties of undefined (reading 'getUserMaps')

### ISSUE THREAD

**Issue by scheelings** [ryanblenis/MeshCentral-RoutePlus#18]
Hi,
After installing the plugin (and restarting MeshCentral) I still get the error: "Internal Server Error" in MeshCentral.
When I check the mesherrors.txt I noticed the following error:
```
TypeError: Cannot read properties of undefined (reading 'getUserMaps')
    at Object.obj.handleAdminReq (/home/danny/meshcentral/meshcentral-data/plugins/routeplus/routeplus.js:213:20)
    at Object.obj.handleAdminReq (/home/danny/meshcentral/node_modules/meshcentral/pluginHandler.js:522:40)
    at obj.handlePluginAdminReq (/home/danny/meshcentral/node_modules/meshcentral/webserver.js:5376:34)
    at Layer.handle [as handle_request] (/home/danny/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/danny/meshcentral/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/danny/meshcentral/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/danny/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /home/danny/meshcentral/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/danny/meshcentral/node_modules/express/lib/router/index.js:335:12)
    at next (/home/danny/meshcentral/node_modules/express/lib/router/index.js:275:10)
```

I have MeshCentral running on Ubuntu 18.04.3!

Do you have any idea what the problem is?

Thx,
Danny

**Comment by SpookOz** [comment]
Same issue on all Ryan's plugins with the new MC version.

**Comment by SpookOz** [comment]
Ryan has published a new version which fixed this (at least for me). Thanks Ryan!

**Comment by Nick-X** [comment]
Hi, is anyone alive here?)
The same problem again on MC release 1.1.35

Error log:
```
-------- 12/25/2024, 8:23:40 AM ---- 1.1.35 --------

TypeError: Cannot read properties of undefined (reading 'getUserMaps')
    at obj.handleAdminReq (/home/mcuser/meshcentral/meshcentral-data/plugins/routeplus/routeplus.js:213:20)
    at obj.handleAdminReq (/home/mcuser/meshcentral/node_modules/meshcentral/pluginHandler.js:527:40)
    at obj.handlePluginAdminReq (/home/mcuser/meshcentral/node_modules/meshcentral/webserver.js:6174:34)
    at Layer.handle [as handle_request] (/home/mcuser/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mcuser/meshcentral/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/home/mcuser/meshcentral/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/home/mcuser/meshcentral/node_modules/express/lib/router/layer.js:95:5)
    at /home/mcuser/meshcentral/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/mcuser/meshcentral/node_modules/express/lib/router/index.js:346:12)
    at next (/home/mcuser/meshcentral/node_modules/express/lib/router/index.js:280:10)

```
